### ISSUE TITLE
发现无法正常使用……

### ISSUE THREAD

**Issue by refengs** [QdghJ/burp_data_collector#2]
mysql是 5.5.53版本的
export finish!
connect success!
export finish!
java.sql.SQLSyntaxErrorException: Table 'data_collect.host_path_map' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'data_collect.host_sub_map' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'data_collect.host_full_path_map' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'data_collect.host_full_path_map' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'data_collect.host_full_path_map' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'data_collect.host_full_path_map' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'data_collect.host_path_map' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'data_collect.host_full_path_map' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'data_collect.host_full_path_map' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'data_collect.host_full_path_map' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'data_collect.host_path_map' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'data_collect.host_path_map' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'data_collect.host_full_path_map' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'data_collect.host_full_path_map' doesn't exist
export finish!
export finish!

**Comment by littleheary** [comment]
你解决了么？我也是差不多的情况

**Comment by refengs** [comment]
mysql版本换个高点的就好了，我现在用的是5.7.26的就没问题
